# https://yaml.org/type/float.html
data:
  train_manifest: data/manifest.train
  dev_manifest: data/manifest.dev
  test_manifest: data/manifest.test
  mean_std_filepath: data/mean_std.npz
  vocab_filepath: data/vocab.txt 
  augmentation_config: conf/augmentation.config
  batch_size: 64 # one gpu
  max_duration: 27.0
  min_duration: 0.0
  specgram_type: linear
  target_sample_rate: 16000
  max_freq: None
  n_fft: None
  stride_ms: 10.0
  window_ms: 20.0
  use_dB_normalization: True
  target_dB: -20
  random_seed: 0
  keep_transcription_text: False
  sortagrad: True 
  shuffle_method: batch_shuffle
  num_workers: 0
model:
  num_conv_layers: 2
  num_rnn_layers: 3
  rnn_layer_size: 1024
  use_gru: True 
  share_rnn_weights: False 
training:
  n_epoch: 30
  lr: 5e-4
  lr_decay: 0.83
  weight_decay: 1e-06
  global_grad_clip: 5.0
  max_iteration: 500000
  plot_interval: 1000
  save_interval: 1000
  valid_interval: 1000
decoding:
  batch_size: 128
  error_rate_type: cer 
  decoding_method: ctc_beam_search
  lang_model_path: models/lm/zh_giga.no_cna_cmn.prune01244.klm
  alpha: 2.6
  beta: 5.0
  beam_size: 300
  cutoff_prob: 0.99 
  cutoff_top_n: 40
  num_proc_bsearch: 8
