# This is the parameter configuration file for PaddleSpeech Serving.

##################################################################
#                     SERVER SETTING                             #
##################################################################
host: '0.0.0.0'
port: 8090

##################################################################
#                     CONFIG FILE                                #
##################################################################
# The engine_type of speech task needs to keep the same type as the config file of speech task.
# E.g: The engine_type of asr is 'python', the engine_backend of asr is 'XX/asr.yaml'
# E.g: The engine_type of asr is 'inference', the engine_backend of asr is 'XX/asr_pd.yaml'
#
# add engine type (Options: python, inference) 
engine_type:
    asr: 'python'
    tts: 'python'

# add engine backend type (Options: asr, tts) and config file here.
# Adding a speech task to engine_backend means starting the service.
engine_backend:
    asr: 'conf/asr/asr.yaml'
    tts: 'conf/tts/tts.yaml'
