# This is the parameter configuration file for PaddleSpeech Serving.

#################################################################################
#                             SERVER SETTING                                    #
#################################################################################
host: 0.0.0.0
port: 8090

# The task format in the engin_list is: <speech task>_<engine type>
# protocol = ['http'] (only one can be selected). 
# http only support offline engine type.
protocol: 'http'
engine_list: ['vector_python']


#################################################################################
#                                ENGINE CONFIG                                  #
#################################################################################

################################### Vector ######################################
################### Vector task: spk; engine_type: python #######################
vector_python:
    task: spk
    model_type: 'ecapatdnn_voxceleb12'
    sample_rate: 16000
    cfg_path: # [optional]
    ckpt_path: # [optional]
    device: # set 'gpu:id' or 'cpu'




