
batch_size: 1
error_rate_type: char-bleu
decoding_method: fullsentence  # 'fullsentence', 'simultaneous'
beam_size: 10
word_reward: 0.7
maxlenratio: 0.3
decoding_chunk_size: -1 # decoding chunk size. Defaults to -1.
    # <0: for decoding, use full chunk.
    # >0: for decoding, use fixed chunk size as set.
    # 0: used for training, it's prohibited here. 
num_decoding_left_chunks: -1  # number of left chunks for decoding. Defaults to -1.
simulate_streaming: False  # simulate streaming inference. Defaults to False.