model_module: transformer

data:
    unit_type: spm

model:
    n_vocab: 5002
    pos_enc: null
    embed_unit: 128
    att_unit: 512
    head: 8
    unit: 2048
    layer: 16
    dropout_rate: 0.5
    emb_dropout_rate: 0.0
    att_dropout_rate: 0.0
    tie_weights: False 

decoding:
    batch_size: 30
    num_workers: 2
