data:
  dataset_type: Bert
  train_path: /data4/mahaoxin/PaddleSpeechTask/examples/punctuation_restoration/chinese/data/iwslt2012_zh/train
  dev_path: /data4/mahaoxin/PaddleSpeechTask/examples/punctuation_restoration/chinese/data/iwslt2012_zh/dev
  test_path: /data4/mahaoxin/PaddleSpeechTask/examples/punctuation_restoration/chinese/data/iwslt2012_zh/test2012_revise
  data_params: 
    pretrained_token: bert-base-chinese
    punc_path: /data4/mahaoxin/PaddleSpeechTask/examples/punctuation_restoration/chinese/data/iwslt2012_zh/punc_vocab
    seq_len: 100
  batch_size: 64
  sortagrad: True 
  shuffle_method: batch_shuffle
  num_workers: 0

checkpoint:
  kbest_n: 5
  latest_n: 10
  metric_type: F1


model_type: BertBLSTM
model_params:
  pretrained_token: bert-base-chinese
  output_size: 4
  dropout: 0.0
  bert_size: 768
  blstm_size: 128
  num_blstm_layers: 2
  init_scale: 0.1

# model_type: BertChLinear
# model_params: bert-base-chinese
#   pretrained_token:
#   output_size: 4
#   dropout: 0.0
#   bert_size: 768

training:
  n_epoch: 100
  lr: !!float 1e-5
  lr_decay: 1.0 
  weight_decay: !!float 1e-06
  global_grad_clip: 5.0
  log_interval: 10
  log_path: /data4/mahaoxin/PaddleSpeechTask/examples/punctuation_restoration/chinese/log/bertBLSTM_zh0812.log

testing:
  log_path: /data4/mahaoxin/PaddleSpeechTask/examples/punctuation_restoration/chinese/log/test_bertBLSTM_zh0812.log

