log_dir: "logs"
save_freq: 20
device: "cuda"
epochs: 180
batch_size: 48
pretrained_model: ""
train_data: "asr_train_list.txt"
val_data: "asr_val_list.txt"

dataset_params:
  data_augmentation: true

preprocess_parasm:
  sr: 24000
  spect_params:
    n_fft: 2048
    win_length: 1200
    hop_length: 300
  mel_params:
    n_mels: 80

model_params:
   input_dim: 80
   hidden_dim: 256
   n_token: 80
   token_embedding_dim: 256

optimizer_params:
  lr: 0.0005