data:
  dataset_type: Bert
  train_path: /data4/mahaoxin/PaddleSpeechTask/examples/punctuation_restoration/english/data/iwslt2012_en/train
  dev_path: /data4/mahaoxin/PaddleSpeechTask/examples/punctuation_restoration/english/data/iwslt2012_en/dev
  test_path: /data4/mahaoxin/PaddleSpeechTask/examples/punctuation_restoration/english/data/iwslt2012_en/test2011
  data_params: 
    pretrained_token: bert-base-uncased  #english
    punc_path: /data4/mahaoxin/PaddleSpeechTask/examples/punctuation_restoration/english/data/iwslt2012_en/punc_vocab
    seq_len: 50
  batch_size: 32
  sortagrad: True 
  shuffle_method: batch_shuffle
  num_workers: 0

checkpoint:
  kbest_n: 10
  latest_n: 10

model_type: BertBLSTM
model_params:
  pretrained_token: bert-base-uncased
  output_size: 4
  dropout: 0.0
  bert_size: 768
  blstm_size: 128
  num_blstm_layers: 2
  init_scale: 0.2
# model_type: BertChLinear
# model_params:
#   pretrained_token: bert-large-uncased
#   output_size: 4
#   dropout: 0.0
#   bert_size: 768

training:
  n_epoch: 100
  lr: !!float 1e-5
  lr_decay: 1.0 
  weight_decay: !!float 1e-06
  global_grad_clip: 5.0
  log_interval: 10
  log_path: log/bertBLSTM_base0812.log

testing:
  log_path: log/testbertBLSTM_base0812.log


