# https://yaml.org/type/float.html
###########################################
#                   Data                  #
###########################################
train_manifest: data/manifest.tiny
dev_manifest: data/manifest.tiny
test_manifest: data/manifest.tiny 
min_input_len: 0.0
max_input_len: 30.0
min_output_len: 0.0
max_output_len: 400.0
min_output_input_ratio: 0.05
max_output_input_ratio: 10.0


###########################################
#              Dataloader                 #
###########################################
mean_std_filepath: data/mean_std.json
unit_type: char
vocab_filepath: data/lang_char/vocab.txt
augmentation_config: conf/augmentation.json
random_seed: 0
spm_model_prefix: 
spectrum_type: linear
feat_dim: 161
delta_delta: False
stride_ms: 10.0
window_ms: 20.0
n_fft: None
max_freq: None
target_sample_rate: 16000
use_dB_normalization: True
target_dB: -20
dither: 1.0
keep_transcription_text: False
sortagrad: True 
shuffle_method: batch_shuffle
num_workers: 0
batch_size: 4
  
############################################
#           Network Architecture           #
############################################
num_conv_layers: 2
num_rnn_layers: 4
rnn_layer_size: 2048
rnn_direction: forward
num_fc_layers: 2
fc_layers_size_list: 512, 256
use_gru: True 
blank_id: 0
  

###########################################
#                Training                 #
###########################################
n_epoch: 5
accum_grad: 1
lr: 1.0e-5 
lr_decay: 1.0 
weight_decay: 1.0e-6
global_grad_clip: 5.0
log_interval: 1
checkpoint:
  kbest_n: 3
  latest_n: 2

